// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package sources

import (
	"github.com/golang/mock/gomock"
	"github.com/rs/zerolog"
)

// Injectors from wire.go:

func NewGitlab(log *zerolog.Logger, cfg *Config) Source {
	sourcesGlIntr := newGitlabInteraction()
	sourcesGitlabSource := &gitlabSource{
		logger:           log,
		cfg:              cfg,
		interactionsFunc: sourcesGlIntr,
	}
	return sourcesGitlabSource
}

func NewTestGitlab(ctrl *gomock.Controller, log *zerolog.Logger, cfg *Config, pager glIntr) Source {
	sourcesGitlabSource := &gitlabSource{
		logger:           log,
		cfg:              cfg,
		interactionsFunc: pager,
	}
	return sourcesGitlabSource
}
